POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
    "username":"J.P l'agitateur",
    "email": "lagitateurpz@gmail.com",
    "birthday": "21/06/1978", 
    "password": "molotov"

}
###

POST http://localhost:3000/show/submit HTTP/1.1
Content-Type: application/json


###

GET http://localhost:3000/list/show HTTP/1.1